### ISSUE TITLE
Name conflict with Bret Terpstra's Marked app

### ISSUE THREAD

**Issue by jrk** [ceramic/markedit#1]
The name of this app is probably, at the very least, not cool given the well established peer in the exact same space): http://marked2app.com

**Comment by eudoxia0** [comment]
Odd. I remember the website perfectly but confused it with Mou, or whatever that other Mac Markdown editor was. I'll change it when I have time to search/replace the docs.

**Comment by CameronBanga** [comment]
+1 Awesome on @eudoxia0 for above. Saw this project and liked how it looked, but name obviously bothered me. Best of luck on the project though, def will be checking it out ,whatever the new name is.
